package playercenter.model;

// Generated Apr 1, 2011 11:25:16 AM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name = "device_blacklist", catalog = "pc_city")
public class DeviceBlacklist implements java.io.Serializable {

	private int id;
	private String device;

	public DeviceBlacklist() {
	}

	public DeviceBlacklist(int id) {
		this.id = id;
	}

	public DeviceBlacklist(int id, String device) {
		this.id = id;
		this.device = device;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "device", length = 32)
	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

}
