package com.youai.gamemis.model;

// Generated 2011-6-9 12:23:00 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * MisGrouppriv generated by hbm2java
 */
@Entity
@Table(name = "mis_grouppriv")
public class MisGrouppriv implements java.io.Serializable {

	private String id;
	private String groupId;
	private String privId;
	private Date createAt;
	private String createBy;
	private int addPriv=0;
	private int queryPriv=0;
	private int modifyPriv=0;
	private int deletePriv=0;

	public MisGrouppriv() {
	}



	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GenericGenerator(name="idGenerator", strategy="uuid") 
	@GeneratedValue(generator="idGenerator")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "group_id", length = 32, nullable = false)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "priv_id", length = 32,  nullable = false)
	public String getPrivId() {
		return this.privId;
	}

	public void setPrivId(String privId) {
		this.privId = privId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Column(name = "create_by", length = 32, nullable = false)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}


	@Column(name = "add_priv")
	public int getAddPriv() {
		return addPriv;
	}



	public void setAddPriv(int addPriv) {
		this.addPriv = addPriv;
	}


	@Column(name = "query_priv")
	public int getQueryPriv() {
		return queryPriv;
	}



	public void setQueryPriv(int queryPriv) {
		this.queryPriv = queryPriv;
	}


	@Column(name = "modify_priv")
	public int getModifyPriv() {
		return modifyPriv;
	}



	public void setModifyPriv(int modifyPriv) {
		this.modifyPriv = modifyPriv;
	}


	@Column(name = "delete_priv")
	public int getDeletePriv() {
		return deletePriv;
	}



	public void setDeletePriv(int deletePriv) {
		this.deletePriv = deletePriv;
	}
	
	

}
