package com.youai.gamemis.model;

//Generated 2012-9-4 16:23:26 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* MisLog generated by hbm2java
*/
@Entity
@Table(name = "mis_log")
public class MisLog implements java.io.Serializable {

	private Integer id;
	private String adminName;
	private Integer actionType;
	private Integer targetId;
	private String detail;
	private String targetName;
	private Long oldValue;
	private Long newValue;
	private Date createdAt;
	private String opTable;
	private String opField;
	private String sOldValue;
	private String sNewValue;
	private Integer opType;
	private Integer opCategory;
	private Integer ownerId;
	public MisLog() {
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "admin_name", length = 32)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "action_type")
	public Integer getActionType() {
		return this.actionType;
	}

	public void setActionType(Integer actionType) {
		this.actionType = actionType;
	}

	@Column(name = "target_id")
	public Integer getTargetId() {
		return this.targetId;
	}

	public void setTargetId(Integer targetId) {
		this.targetId = targetId;
	}

	@Column(name = "detail", length = 128)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	

	@Column(name="old_value")
	public Long getOldValue() {
		return oldValue;
	}


	public void setOldValue(Long oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name="new_value")
	public Long getNewValue() {
		return newValue;
	}


	public void setNewValue(Long newValue) {
		this.newValue = newValue;
	}

	@Column(name="target_name")
	public String getTargetName() {
		return targetName;
	}


	public void setTargetName(String targetName) {
		this.targetName = targetName;
	}

	@Column(name="created_at")
	public Date getCreatedAt() {
		return createdAt;
	}


	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name="op_table")
	public String getOpTable() {
		return opTable;
	}


	public void setOpTable(String opTable) {
		this.opTable = opTable;
	}

	
	@Column(name="op_field")
	public String getOpField() {
		return opField;
	}


	public void setOpField(String opField) {
		this.opField = opField;
	}

	@Column(name="s_old_value")
	public String getSOldValue() {
		return sOldValue;
	}

	public void setSOldValue(String sOldValue) {
		this.sOldValue = sOldValue;
	}

	@Column(name="s_new_value")
	public String getSNewValue() {
		return sNewValue;
	}


	public void setSNewValue(String sNewValue) {
		this.sNewValue = sNewValue;
	}

	@Column(name="op_type")
	public Integer getOpType() {
		return opType;
	}

	public void setOpType(Integer opType) {
		this.opType = opType;
	}

	@Column(name="op_category")
	public Integer getOpCategory() {
		return opCategory;
	}


	public void setOpCategory(Integer opCategory) {
		this.opCategory = opCategory;
	}

	@Column(name="owner_id")
	public Integer getOwnerId() {
		return ownerId;
	}


	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	
	
	
	
	
	
}

