package com.youai.gamemis.model;

// Generated 2011-6-9 12:23:00 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
 * MisPrivilege generated by hbm2java
 */
@Entity
@Table(name = "mis_privilege")
public class MisPrivilege implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String name;
	private Integer type;
	private String mentityId;
	private String url;
	private Integer actionType;
	private Date createAt;
	private String createBy;
	private Integer position;
	private Integer parentNavId;
	@Transient
	private Integer addPriv=0;
	@Transient
	private Integer deletePriv=0;
	@Transient
	private Integer queryPriv=0;
	@Transient
	private Integer modifyPriv=0;
	@Transient
	private Integer owned=0;
	@Transient
	private String realUrl;
	@Transient
	private List<MisPrivilege> privs;
	@Transient
	private int navType=0;
	
	@Transient
	public String getRealUrl() {
		return realUrl;
	}
	@Transient
	public void setRealUrl(String realUrl) {
		this.realUrl = realUrl;
	}
	@Column(name = "position")
	public Integer getPosition() {
		return position;
	}
	@Transient
	public Integer getOwned() {
		return owned;
	}
	@Transient
	public void setOwned(Integer owned) {
		this.owned = owned;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	public MisPrivilege() {
	}

	public MisPrivilege(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public MisPrivilege(String id, String name, Integer type, String mentityId,
			String url, Integer actionType, Date createAt, String createBy) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.mentityId = mentityId;
		this.url = url;
		this.actionType = actionType;
		this.createAt = createAt;
		this.createBy = createBy;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	@GenericGenerator(name="idGenerator", strategy="uuid") 
	@GeneratedValue(generator="idGenerator")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "mentity_id", length = 32)
	public String getMentityId() {
		return this.mentityId;
	}

	public void setMentityId(String mentityId) {
		this.mentityId = mentityId;
	}

	@Column(name = "url", length = 1024)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "action_type")
	public Integer getActionType() {
		return this.actionType;
	}

	public void setActionType(Integer actionType) {
		this.actionType = actionType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Column(name = "create_by", length = 32)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	
	@Column(name = "parent_nav_id")
	public Integer getParentNavId() {
		return parentNavId;
	}
	public void setParentNavId(Integer parentNavId) {
		this.parentNavId = parentNavId;
	}
	@Transient
	public Integer getAddPriv() {
		return addPriv;
	}
	public void setAddPriv(Integer addPriv) {
		this.addPriv = addPriv;
	}
	@Transient
	public Integer getDeletePriv() {
		return deletePriv;
	}
	public void setDeletePriv(Integer deletePriv) {
		this.deletePriv = deletePriv;
	}
	@Transient
	public Integer getQueryPriv() {
		return queryPriv;
	}
	public void setQueryPriv(Integer queryPriv) {
		this.queryPriv = queryPriv;
	}
	@Transient
	public Integer getModifyPriv() {
		return modifyPriv;
	}
	public void setModifyPriv(Integer modifyPriv) {
		this.modifyPriv = modifyPriv;
	}
	
	
	@Transient
	public int getNavType() {
		return navType;
	}
	public void setNavType(int navType) {
		this.navType = navType;
	}
	
	@Transient
	public List<MisPrivilege> getPrivs() {
		return privs;
	}
	public void setPrivs(List<MisPrivilege> privs) {
		this.privs = privs;
	}
	
	
	
}
