package com.youai.gamemis.model;

// Generated 2011-6-9 12:23:00 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * MisUsergroup generated by hbm2java
 */
@Entity
@Table(name = "mis_usergroup")
public class MisUsergroup implements java.io.Serializable {

	private String id;
	private Date createAt;
	private Date updateAt;
	private String updateBy;
	private String createBy;
	private String groupId;
	private String userId;

	public MisUsergroup() {
	}

	public MisUsergroup(String id, String groupId, String userId) {
		this.id = id;
		this.groupId = groupId;
		this.userId = userId;
	}

	public MisUsergroup(String id, Date createAt, Date updateAt,
			String updateBy, String createBy, String groupId, String userId) {
		this.id = id;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.updateBy = updateBy;
		this.createBy = createBy;
		this.groupId = groupId;
		this.userId = userId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	@GenericGenerator(name="idGenerator", strategy="uuid") 
	@GeneratedValue(generator="idGenerator")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "update_by", length = 32)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "create_by", length = 32)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "group_id", nullable = false, length = 32)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "user_id", nullable = false, length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
