package com.youai.gamemis.model;

// Generated 2013-5-7 20:48:07 by Hibernate Tools 3.3.0.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ParentNav generated by hbm2java
 */
@Entity
@Table(name = "parent_nav", catalog="dzm_mis",  uniqueConstraints = @UniqueConstraint(columnNames = "idx"))
public class ParentNav implements java.io.Serializable {

	/**
	 * 
	 */
	@Transient
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer idx;
	private String name;
	private Integer position;
	@Transient
	private List<MisPrivilege> privs;

	public ParentNav() {
	}

	public ParentNav(Integer idx, String name, Integer position) {
		this.idx = idx;
		this.name = name;
		this.position = position;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "idx", unique = true)
	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}
	@Transient
	public List<MisPrivilege> getPrivs() {
		return privs;
	}
	
	public void setPrivs(List<MisPrivilege> privs) {
		this.privs = privs;
	}
	
	
}
