package com.youai.gamemis.model;

// Generated 2011-5-12 13:31:50 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StatPaymentItem generated by hbm2java
 */
@Entity
@Table(name = "stat_payment_item")
public class StatPaymentItem implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	private String productId;
	private String statItem;
	private String title;
	private Float price;
	private Integer statUiNum;
	private String dataType;

	public StatPaymentItem() {
	}

	public StatPaymentItem(String productId, String statItem, String title) {
		this.productId = productId;
		this.statItem = statItem;
		this.title = title;
	}

	public StatPaymentItem(String productId, String statItem, String title,
			Float price, Integer statUiNum, String dataType) {
		this.productId = productId;
		this.statItem = statItem;
		this.title = title;
		this.price = price;
		this.statUiNum = statUiNum;
		this.dataType = dataType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "product_id", nullable = false, length = 64)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "stat_item", nullable = false, length = 64)
	public String getStatItem() {
		return this.statItem;
	}

	public void setStatItem(String statItem) {
		this.statItem = statItem;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "price", precision = 10)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "stat_ui_num")
	public Integer getStatUiNum() {
		return this.statUiNum;
	}

	public void setStatUiNum(Integer statUiNum) {
		this.statUiNum = statUiNum;
	}

	@Column(name = "data_type", length = 64)
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

}
