package com.youai.gamemis.model;

// Generated 2011-5-13 16:52:29 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StatPlayerResult generated by hbm2java
 */
@Entity
@Table(name = "stat_player_result")
public class StatPlayerResult implements java.io.Serializable, Comparable<StatPlayerResult>{

	private Integer id;
	private Date statDate;
	private Integer last1dAdd=0;
	private Integer last1dDau=0;
	private Integer last30dDau=0;
	private Integer dau1dreg=0;
	private Integer lose3day=0;
	private Integer lose5day=0;
	private Integer playerSum=0;
	private Integer inactiveUser=0;
	private Float inactiveUserLevel=0f;
	private Float avg30dauLevel=0f;
	private Float dau1dregRatio=0f;
	private Float dau2dregRatio=0f; 
	public StatPlayerResult() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "stat_date", length = 10)
	public Date getStatDate() {
		return this.statDate;
	}

	public void setStatDate(Date statDate) {
		this.statDate = statDate;
	}

	@Column(name = "last1d_add")
	public Integer getLast1dAdd() {
		return this.last1dAdd;
	}

	public void setLast1dAdd(Integer last1dAdd) {
		this.last1dAdd = last1dAdd;
	}

	@Column(name = "last1d_dau")
	public Integer getLast1dDau() {
		return this.last1dDau;
	}

	public void setLast1dDau(Integer last1dDau) {
		this.last1dDau = last1dDau;
	}

	@Column(name = "last30d_dau")
	public Integer getLast30dDau() {
		return this.last30dDau;
	}

	public void setLast30dDau(Integer last30dDau) {
		this.last30dDau = last30dDau;
	}

	@Column(name = "dau_1dreg")
	public Integer getDau1dreg() {
		return this.dau1dreg;
	}

	public void setDau1dreg(Integer dau1dreg) {
		this.dau1dreg = dau1dreg;
	}

	@Column(name = "lose_3day")
	public Integer getLose3day() {
		return this.lose3day;
	}

	public void setLose3day(Integer lose3day) {
		this.lose3day = lose3day;
	}

	@Column(name = "lose_5day")
	public Integer getLose5day() {
		return this.lose5day;
	}

	public void setLose5day(Integer lose5day) {
		this.lose5day = lose5day;
	}

	@Column(name = "player_sum")
	public Integer getPlayerSum() {
		return this.playerSum;
	}

	public void setPlayerSum(Integer playerSum) {
		this.playerSum = playerSum;
	}

	@Column(name = "inactive_user")
	public Integer getInactiveUser() {
		return this.inactiveUser;
	}

	public void setInactiveUser(Integer inactiveUser) {
		this.inactiveUser = inactiveUser;
	}

	@Column(name = "inactive_user_level", precision = 4)
	public Float getInactiveUserLevel() {
		return this.inactiveUserLevel;
	}

	public void setInactiveUserLevel(Float inactiveUserLevel) {
		this.inactiveUserLevel = inactiveUserLevel;
	}

	@Column(name = "avg_30dau_level", precision = 4)
	public Float getAvg30dauLevel() {
		return this.avg30dauLevel;
	}

	public void setAvg30dauLevel(Float avg30dauLevel) {
		this.avg30dauLevel = avg30dauLevel;
	}
	
	@Column(name="dau_1dreg_ratio",precision = 4)
	public Float getDau1dregRatio() {
		return dau1dregRatio;
	}



	public void setDau1dregRatio(Float dau1dregRatio) {
		this.dau1dregRatio = dau1dregRatio;
	}

	
	@Column(name="dau_2dreg_ratio",precision = 4)
	public Float getDau2dregRatio() {
		return dau2dregRatio;
	}



	public void setDau2dregRatio(Float dau2dregRatio) {
		this.dau2dregRatio = dau2dregRatio;
	}



	public void add( StatPlayerResult b ){
		this.avg30dauLevel = (this.avg30dauLevel * this.playerSum +  b.avg30dauLevel  * b.playerSum ) / ( this.playerSum + b.playerSum );
		this.dau1dreg = this.dau1dreg + b.dau1dreg;
		this.inactiveUser = this.inactiveUser + b.inactiveUser;
		this.inactiveUserLevel = (this.inactiveUserLevel* this.inactiveUser + b.inactiveUserLevel * b.inactiveUser) / ( this.inactiveUser + b.inactiveUser);
		this.last1dAdd = this.last1dAdd + b.last1dAdd;
		this.last1dDau = this.last1dDau + b.last1dDau;
		this.last30dDau = this.last30dDau + b.last30dDau;
		this.lose3day = this.lose3day + b.lose3day;
		this.lose5day = this.lose5day + b.lose5day;
		this.playerSum = this.playerSum + b.playerSum;
	}
	
	
	public int compareTo(StatPlayerResult arg0) {
		// TODO Auto-generated method stub
		return this.statDate.compareTo( arg0.getStatDate() );
	}

}
