package com.youai.gamemis.model;

// Generated 2011-5-11 19:04:00 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * StatPayment generated by hbm2java
 */

public class StatUIPayment implements java.io.Serializable, Comparable<StatUIPayment> {

	private Integer id;
	private Integer product1=0;
	private Integer product2=0;
	private Integer product3=0;
	private Integer product4=0;
	private Integer product5=0;
	private Integer product6=0;
	private Integer product7=0;
	private Integer product8=0;
	private Date statDate;
	private Integer payuser1day=0;

	public StatUIPayment() {
	}

	public StatUIPayment(Integer product1, Integer product2, Integer product3,
			Integer product4, Integer product5, Integer product6,
			Integer product7, Integer product8, Date statDate,
			Integer payuser1day) {
		this.product1 = product1;
		this.product2 = product2;
		this.product3 = product3;
		this.product4 = product4;
		this.product5 = product5;
		this.product6 = product6;
		this.product7 = product7;
		this.product8 = product8;
		this.statDate = statDate;
		this.payuser1day = payuser1day;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public Integer getProduct1() {
		return this.product1;
	}

	public void setProduct1(Integer product1) {
		this.product1 = product1;
	}

	
	public Integer getProduct2() {
		return this.product2;
	}

	public void setProduct2(Integer product2) {
		this.product2 = product2;
	}

	
	public Integer getProduct3() {
		return this.product3;
	}

	public void setProduct3(Integer product3) {
		this.product3 = product3;
	}

	
	public Integer getProduct4() {
		return this.product4;
	}

	public void setProduct4(Integer product4) {
		this.product4 = product4;
	}

	
	public Integer getProduct5() {
		return this.product5;
	}

	public void setProduct5(Integer product5) {
		this.product5 = product5;
	}

	
	public Integer getProduct6() {
		return this.product6;
	}

	public void setProduct6(Integer product6) {
		this.product6 = product6;
	}

	
	public Integer getProduct7() {
		return this.product7;
	}

	public void setProduct7(Integer product7) {
		this.product7 = product7;
	}

	
	public Integer getProduct8() {
		return this.product8;
	}

	public void setProduct8(Integer product8) {
		this.product8 = product8;
	}

	
	public Date getStatDate() {
		return this.statDate;
	}

	public void setStatDate(Date statDate) {
		this.statDate = statDate;
	}


	public Integer getPayuser1day() {
		return this.payuser1day;
	}

	public void setPayuser1day(Integer payuser1day) {
		this.payuser1day = payuser1day;
	}

	

	public int compareTo(StatUIPayment o) {
		return this.statDate.compareTo( o.statDate ) ;
		
	}

}
