package com.youai.gamemis.model;

// Generated 2011-5-12 13:31:50 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StatPaymentResult generated by hbm2java
 */
@Entity
@Table(name = "stat_payment_result")
public class StatPaymentResult implements java.io.Serializable {

	private Integer id;
	private String resName;
	private Integer resNum;
	private Date statDate;

	public StatPaymentResult() {
	}

	public StatPaymentResult(String resName, Date statDate) {
		this.resName = resName;
		this.statDate = statDate;
	}

	public StatPaymentResult(String resName, Integer resNum, Date statDate) {
		this.resName = resName;
		this.resNum = resNum;
		this.statDate = statDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "res_name", nullable = false, length = 64)
	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	@Column(name = "res_num")
	public Integer getResNum() {
		return this.resNum;
	}

	public void setResNum(Integer resNum) {
		this.resNum = resNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "stat_date", nullable = false, length = 10)
	public Date getStatDate() {
		return this.statDate;
	}

	public void setStatDate(Date statDate) {
		this.statDate = statDate;
	}

}
