package com.youai.gs.common.message.model;

// Generated 2011-5-4 10:49:59 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Bulletin generated by hbm2java
 */
@Entity
@Table(name = "bulletin")
public class Bulletin implements java.io.Serializable {

	/**
	 * 
	 */
	@Transient
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String content;
	private Date createdAt;
	private Date expireAt;
	private String title;
	private Integer type;
	private Integer serverIdx;

	public Bulletin() {
	}

	public Bulletin(Integer id) {
		this.id = id;
	}

	public Bulletin(Integer id, String content, Date createdAt, Date expireAt, String title, Integer type) {
		this.id = id;
		this.content = content;
		this.createdAt = createdAt;
		this.expireAt = expireAt;
		this.type = type;
		this.title = title;
	}

	@Column(name="server_idx")
	public Integer getServerIdx() {
		return serverIdx;
	}

	public void setServerIdx(Integer serverIdx) {
		this.serverIdx = serverIdx;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "content", length = 1024)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_at", length = 19)
	public Date getExpireAt() {
		return this.expireAt;
	}

	public void setExpireAt(Date expireAt) {
		this.expireAt = expireAt;
	}

	@Column(name = "title", length = 64)
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "type")
	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	
}
