package com.youai.gs.common.message.model;

// Generated Apr 3, 2011 4:49:30 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.*;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * FeedbackThread generated by hbm2java
 */
@Entity
@Table(name = "feedback_thread")
public class FeedbackThread implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "player_key")
	private Integer playerKey;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	private Date createdAt;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	private Date updatedAt;
	@Column(name = "player_name", length=128)
	private String playerName;
	@Column(name = "ignored")
	private Integer ignored;
	@Column(name = "replied" )
	private Integer replied;
	@Column(name = "player_gamekey")
	private Integer playerGamekey;
	@Column(name= "head_id")
	private Integer headId;
	@Column(name="last_op_admin", length=64)
	private String lastOpAdmin;
	@Column(name= "feedback_type" )
	private Integer feedbackType;
	@Column(name = "game_id")
	private String gameId;
	@Column(name = "payed")
	private Integer payed = 0;
	
	public Integer getPayed() {
		return payed;
	}

	public void setPayed(Integer payed) {
		this.payed = payed;
	}
	public String getGameId() {
		return gameId;
	}
	public void setGameId(String gameId) {
		this.gameId = gameId;
	}

	@Transient
	private String feedbackTypeName;
	
	@Transient
	public String getFeedbackTypeName() {
		return feedbackTypeName;
	}
	@Transient
	public void setFeedbackTypeName(String feedbackTypeName) {
		this.feedbackTypeName = feedbackTypeName;
	}

	public Integer getFeedbackType() {
		return feedbackType;
	}

	public void setFeedbackType(Integer feedbackType) {
		this.feedbackType = feedbackType;
	}

	public String getLastOpAdmin() {
		return lastOpAdmin;
	}

	public void setLastOpAdmin(String lastOpAdmin) {
		this.lastOpAdmin = lastOpAdmin;
	}

	public Integer getHeadId() {
		return headId;
	}

	public void setHeadId(Integer headId) {
		this.headId = headId;
	}

	public Integer getPlayerGamekey() {
		return playerGamekey;
	}

	public void setPlayerGamekey(Integer playerGamekey) {
		this.playerGamekey = playerGamekey;
	}

	public Integer getReplied() {
		return replied;
	}

	public void setReplied(Integer replied) {
		this.replied = replied;
	}

	public Integer getIgnored() {
		return ignored;
	}

	public void setIgnored(Integer ignored) {
		this.ignored = ignored;
	}

	public String getPlayerName() {
		return playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}


	public FeedbackThread() {
	}



	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPlayerKey() {
		return this.playerKey;
	}

	public void setPlayerKey(Integer playerKey) {
		this.playerKey = playerKey;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
