package com.youai.gs.common.message.model;

// Generated Apr 3, 2011 4:49:30 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.*;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FeedbackMessage generated by hbm2java
 */
@Entity
@Table(name = "feedback_message")
public class FeedbackMessage implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "thread_id")
	private Integer threadId;
	@Column(name = "answer")
	private Integer answer;
	@Column(name = "ignored")
	private Integer ignored;
	@Column(name = "replied")
	private Integer replied;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	private Date createdAt;
	@Column(name = "content", length = 1024)
	private String content;
	@Column(name = "head")
	private Integer head;
	@Column(name = "replyer_name", length=64)
	private String replyerName;

	

	public String getReplyerName() {
		return replyerName;
	}

	public void setReplyerName(String replyerName) {
		this.replyerName = replyerName;
	}

	public Integer getHead() {
		return head;
	}

	public void setHead(Integer head) {
		this.head = head;
	}

	public FeedbackMessage() {
	}

	public FeedbackMessage(Integer threadId, Integer answer, Integer ignored,
			Integer replied, Date createdAt, String content) {
		this.threadId = threadId;
		this.answer = answer;
		this.ignored = ignored;
		this.replied = replied;
		this.createdAt = createdAt;
		this.content = content;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getThreadId() {
		return this.threadId;
	}

	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	public Integer getAnswer() {
		return this.answer;
	}

	public void setAnswer(Integer answer) {
		this.answer = (answer);
	}

	public Integer getIgnored() {
		return this.ignored;
	}

	public void setIgnored(Integer ignored) {
		this.ignored = (ignored);
	}

	public Integer getReplied() {
		return this.replied;
	}

	public void setReplied(Integer replied) {
		this.replied = (replied);
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
