package com.youai.gs.common.message.model;

// Generated 2011-5-4 10:49:59 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MessageThread generated by hbm2java
 */
@Entity
@Table(name = "message_thread")
public class MessageThread implements java.io.Serializable {

	private String id;
	private Date createdAt;
	private Integer origMsgId;
	private String playerKey;
	private String playerName;
	private Date updatedAt;
	private String title;

	public MessageThread() {
	}

	public MessageThread(Date createdAt, Integer origMsgId, String playerKey,
			String playerName, Date updatedAt, String title) {
		this.createdAt = createdAt;
		this.origMsgId = origMsgId;
		this.playerKey = playerKey;
		this.playerName = playerName;
		this.updatedAt = updatedAt;
		this.title = title;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "orig_msg_id")
	public Integer getOrigMsgId() {
		return this.origMsgId;
	}

	public void setOrigMsgId(Integer origMsgId) {
		this.origMsgId = origMsgId;
	}

	@Column(name = "player_key", length = 32)
	public String getPlayerKey() {
		return this.playerKey;
	}

	public void setPlayerKey(String playerKey) {
		this.playerKey = playerKey;
	}

	@Column(name = "player_name", length = 128)
	public String getPlayerName() {
		return this.playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
