package com.youai.gs.common.message.model;

// Generated Apr 3, 2011 4:49:30 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.*;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bulletin generated by hbm2java
 */
@Entity
@Table(name = "notification")
public class Notification implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "content", length = 1024)
	private String content;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	private Date createdAt = new Date();
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_at", length = 19)
	private Date expireAt = new Date();
	
	@Column(name = "country_code", length = 5)
	private String countryCode = "ALL";
	
	@Column(name = "locale", length = 5 )
	private String locale = "en";
	
	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public Notification() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer key) {
		this.id = key;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getExpireAt() {
		return this.expireAt;
	}

	public void setExpireAt(Date expireAt) {
		this.expireAt = expireAt;
	}

	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

}
