package com.youai.gs.common.message.model;

// Generated Apr 3, 2011 4:49:30 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlayerBulletin generated by hbm2java
 */
@Entity
@Table(name = "player_bulletin")
public class PlayerBulletin implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "player_key")
	private Integer playerKey;
	@Column(name = "bulletin_key")
	private Integer bulletinKey;

	public PlayerBulletin() {
	}

	public PlayerBulletin(Integer playerKey, Integer bulletinKey) {
		this.playerKey = playerKey;
		this.bulletinKey = bulletinKey;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPlayerKey() {
		return this.playerKey;
	}

	public void setPlayerKey(Integer playerKey) {
		this.playerKey = playerKey;
	}

	public Integer getBulletinKey() {
		return this.bulletinKey;
	}

	public void setBulletinKey(Integer bulletinKey) {
		this.bulletinKey = bulletinKey;
	}

}
