package com.youai.gs.common.payment.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2011-5-3 19:17:35 by Hibernate Tools 3.3.0.GA

/**
 * TapjoyPayment generated by hbm2java
 */
@Entity
@Table(name = "tapjoy_payment")
public class TapjoyPayment implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column( name = "player_id")
	private Integer playerId;
	@Column( name = "currency")
	private Integer currency;
	@Column( name = "tjid")
	private String tjid;
	@Column( name = "verifier")
	private String verifier;

	public TapjoyPayment() {
	}

	public TapjoyPayment(Integer id) {
		this.id = id;
	}

	

	public Integer getPlayerId() {
		return playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



	public Integer getCurrency() {
		return this.currency;
	}

	public void setCurrency(Integer currency) {
		this.currency = currency;
	}

	public String getTjid() {
		return this.tjid;
	}

	public void setTjid(String tjid) {
		this.tjid = tjid;
	}

	public String getVerifier() {
		return this.verifier;
	}

	public void setVerifier(String verifier) {
		this.verifier = verifier;
	}

}
