package com.youai.gs.common.payment.model;

// Generated 2013-6-21 18:37:06 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WiyunPayment2 generated by hbm2java
 */
@Entity
@Table(name = "wiyun_payment2")
public class WiyunPayment2 implements java.io.Serializable {

	private Integer id;
	private String seqId;
	private Integer playerId;
	private Integer serverIdx;
	private String transId;
	private String productId;
	private String money;
	private Integer goodsNum;
	private Integer payResult;
	private String timeStamp;
	private Date createdAt;

	public WiyunPayment2() {
	}

	public WiyunPayment2(Date createdAt) {
		this.createdAt = createdAt;
	}

	public WiyunPayment2(String seqId, Integer playerId, Integer serverIdx, String transId, String productId,
			String money, Integer goodsNum, Integer payResult, String timeStamp, Date createdAt) {
		this.seqId = seqId;
		this.playerId = playerId;
		this.serverIdx = serverIdx;
		this.transId = transId;
		this.productId = productId;
		this.money = money;
		this.goodsNum = goodsNum;
		this.payResult = payResult;
		this.timeStamp = timeStamp;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "seq_id", length = 128)
	public String getSeqId() {
		return this.seqId;
	}

	public void setSeqId(String seqId) {
		this.seqId = seqId;
	}

	@Column(name = "player_id")
	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	@Column(name = "server_idx")
	public Integer getServerIdx() {
		return this.serverIdx;
	}

	public void setServerIdx(Integer serverIdx) {
		this.serverIdx = serverIdx;
	}

	@Column(name = "trans_id", length = 64)
	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	@Column(name = "product_id", length = 64)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "money", length = 64)
	public String getMoney() {
		return this.money;
	}

	public void setMoney(String money) {
		this.money = money;
	}

	@Column(name = "goods_num")
	public Integer getGoodsNum() {
		return this.goodsNum;
	}

	public void setGoodsNum(Integer goodsNum) {
		this.goodsNum = goodsNum;
	}

	@Column(name = "pay_result")
	public Integer getPayResult() {
		return this.payResult;
	}

	public void setPayResult(Integer payResult) {
		this.payResult = payResult;
	}

	@Column(name = "time_stamp", length = 32)
	public String getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(String timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
